# Generated by Django 3.1.2 on 2020-10-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201027_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopes',
            name='article_scope',
            field=models.TextField(verbose_name='Раздел'),
        ),
    ]
