# Generated by Django 3.1.2 on 2020-10-30 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201030_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scope',
            field=models.ManyToManyField(through='articles.Membership', to='articles.Scopes'),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='article',
        ),
        migrations.AddField(
            model_name='membership',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
