# Generated by Django 3.1.2 on 2020-10-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20201030_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_main',
            field=models.BooleanField(null=True),
        ),
    ]
