# Generated by Django 3.1.2 on 2020-10-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201030_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopes',
            name='scope',
            field=models.TextField(choices=[('Город', 'City'), ('Здоровье', 'Health'), ('Культура', 'Culture'), ('Космос', 'Space'), ('Наука', 'Science'), ('Международные отношения', 'Relations')], verbose_name='Раздел'),
        ),
    ]
