# Generated by Django 3.1.2 on 2020-11-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCollection',
            new_name='ProductsCollection',
        ),
    ]
