# Generated by Django 3.1.2 on 2020-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201115_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='оценка'),
        ),
    ]
