# Generated by Django 3.1.2 on 2020-11-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201115_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsfororder',
            old_name='order_id',
            new_name='order',
        ),
    ]
