# Generated by Django 3.1.2 on 2020-11-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201116_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscollection',
            name='products',
            field=models.ManyToManyField(related_name='collections', to='shop.Product'),
        ),
    ]
