# Generated by Django 3.1.2 on 2020-11-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201118_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='customer',
        ),
    ]
