# Generated by Django 3.1.2 on 2020-11-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201118_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsfororder',
            name='sum_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='цена за товары'),
        ),
    ]
