# Generated by Django 3.1.2 on 2020-11-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productsfororder_sum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsfororder',
            name='sum_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена за товары'),
        ),
    ]
