# Generated by Django 3.1.2 on 2020-11-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20201121_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsfororder',
            name='sum_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='цена за товары'),
        ),
    ]
